spring:
application.name: es-teacher-service

jackson:
  serialization.WRITE_DATES_AS_TIMESTAMPS: false

datasource:
  url: jdbc:postgresql://localhost:5432/es_teacher
  username: es_db_teacher
  password: edusys2020
  driver-class-name: org.postgresql.Driver
  schema: classpath:/schema-postgres.sql
  initialization-mode: always
  platform: postgres

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env"]